apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name.pg }}-pv
spec:
  capacity:
    storage: {{ .Values.postgresql.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.postgresql.hostPath }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name.pg }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.storage }}