apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name.pg }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: {{ .Values.postgresql.port }}
  selector:
    app: {{ .Values.name.pg }}