apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name.sq }}-pv
spec:
  capacity:
    storage: {{ .Values.sonarqube.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.sonarqube.hostPath }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name.sq }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sonarqube.storage }}